161225-144218-jrWetterstation-31-INFO-

Wetterstation gestartet

161225-144218-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    rrdtool.update(self.rrdFile,'N:%s:%s' %(self.actTemp,self.actPress))
error: opening 'db/jrWetter.rrd': No such file or directory

161225-144745-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-105146-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-160002-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-160002-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "/home/robert/jrWetterstation/sensors/jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    .byte	0x93
error: opening '../db/jrWetter.rrd': No such file or directory

161231-160502-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-160502-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "/home/robert/jrWetterstation/sensors/jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    .byte	0x93
error: opening '../db/jrWetter.rrd': No such file or directory

161231-161002-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-161002-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "/home/robert/jrWetterstation/sensors/jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    .byte	0x93
error: opening '../db/jrWetter.rrd': No such file or directory

161231-161503-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-161503-jrWetterstation-46-ERROR-Global exception handler: 
Traceback (most recent call last):
  File "/home/robert/jrWetterstation/sensors/jrWetterstation.py", line 39, in <module>
    ky052.save()
  File "/home/robert/jrWetterstation/sensors/KY052_Sensor.py", line 58, in save
    .byte	0x93
error: opening '../db/jrWetter.rrd': No such file or directory

161231-161802-jrWetterstation-31-INFO-

Wetterstation gestartet

161231-162003-jrWetterstation-31-INFO-

Wetterstation gestartet

